import { createStyles, makeStyles } from '@material-ui/core/styles'

const useStyles = makeStyles(() =>
  createStyles({
    root: {
      display: 'flex',
      backgroundColor: '#3C065E',
      height: '100vh',
      borderRadius: 0,
      zIndex: 20,
    },
    main: {
      overflowY: 'hidden',
      height: '100vh',
    },
    details: {
      display: 'flex',
      flexDirection: 'column',
      width: '45%',
      paddingTop: 80,
      paddingLeft: 80,
      textAlign: 'left',
      marginTop: 70,
    },
    title: {
      fontSize: 41,
      fontWeight: 'bold',
      color: '#FFF',
    },
    textTitle: {
      marginTop: 15,
    },
    subtitle: {
      fontSize: 18,
      color: '#FFF',
      width: '79%',
      paddingLeft: 10,
      marginTop: 30,
    },
    svgbanner: {
      width: '43%',
      float: 'right',
      marginTop: -430,
      marginRight: 60,
    },
    btnshire: {
      width: 240,
      marginTop: 60,
      paddingLeft: 10,
      borderRadius: 0,
      fontSize: 26,
      fontWeight: 'bold',
      paddingTop: 10,
      paddingBottom: 10,
      background: '#B918AB',
      border: 0,
      color: 'white',
    },
    zindex: {
      zIndex: 20,
      position: 'relative',
      width: '100%',
    },
    circularbg: {
      width: 330,
      height: 330,
      backgroundColor: '#6C63FF',
      display: 'inline-block',
      opacity: '10%',
      borderRadius: '100%',
      position: 'relative',
      marginTop: -120,
      marginLeft: -60,
      zIndex: 1,
    },
    circularbg2: {
      width: 70,
      height: 70,
      backgroundColor: '#6C63FF',
      display: 'inline-block',
      opacity: '10%',
      borderRadius: '100%',
      position: 'absolute',
      marginTop: -100,
      marginLeft: 40,
      zIndex: 2,
    },
    circularbg3: {
      width: 35,
      height: 35,
      backgroundColor: '#6C63FF',
      display: 'inline-block',
      opacity: '10%',
      borderRadius: '100%',
      position: 'absolute',
      marginTop: -105,
      marginLeft: 90,
      zIndex: 3,
    },
  }),
)

export default useStyles
